# Generated by Django 5.1.7 on 2025-03-13 20:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laborer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('rate', models.FloatField()),
                ('salary', models.FloatField(default='0')),
                ('loan', models.FloatField(default='0')),
                ('after_loan_amount', models.FloatField(default='0')),
                ('deducted_loan', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rate_type', models.CharField(choices=[('daily', 'Daily'), ('hourly', 'Hourly'), ('minute', 'Minute'), ('second', 'Second')], default='daily', max_length=10)),
                ('start_date', models.DateTimeField()),
                ('re_start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Terminated', 'Terminated'), ('Re-enable', 'Re-enable')], default='Active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('days_worked', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('after_paid_amount', models.FloatField(default='0')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('paid_amount', models.FloatField(default='0')),
                ('laborer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payease.laborer')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('validity', models.CharField(choices=[('Done', 'Done'), ('Undone', 'Undone')], default='Done', max_length=10)),
                ('role', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('paid_amount', models.FloatField()),
                ('type_of_payment', models.CharField(choices=[('Loan', 'Loan'), ('Salary', 'Salary')], default='Salary', max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Terminated', 'Terminated'), ('Re-enable', 'Re-enable')], default='Active', max_length=10)),
                ('laborer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payease.laborer')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payease.payment')),
            ],
        ),
    ]
